### ISSUE TITLE
pl_privatelink-proxy and dest_privatelink-proxy not appearing in the dropbox when creating the router

### ISSUE THREAD

**Issue by saurabhakumbhare** [SAP-samples/btp-private-link-approuter#6]
- name: pl_privatelink-proxy
- name: dest_privatelink-proxy

Can you guide what could be the issue ?

**Comment by hterminasyan** [comment]
hi @saurabhakumbhare , 

could you please give me more context on what you are trying, on which step the issue is?

**Comment by hterminasyan** [comment]
hi @saurabhakumbhare , 

sorry for my late response. 
Since the PrivateLink service needs a couple of additional steps to approve the connection from Azure/AWS side, the service should be first initiated (e.g. name tfe-cal-s4-privatelink). After that, once you deploy the router, it will be automatically bound to that instance (pl_privatelink-proxy). The destination on Subaccount you need to add afterward, based on the assigned private hostname.

Hope this helps, 
Kind regards, 
Harut
